### ISSUE TITLE
Possible Compilation Error

### ISSUE THREAD

**Issue by lifeanddeath** [lifeanddeath/oracle-certification-javaSE8-programmer#2]
```
3: String[] strings = { "stringValue" };
4: Object[] objects = strings;
5: String[] againStrings = (String[]) objects;
6: againStrings[0] = new StringBuilder(); // DOES NOT COMPILE
7: objects[0] = new StringBuilder(); // careful!
```

In this example, the answer as follows:

> 
> Line 7 is where this gets interesting. From the point of view of the compiler, this is just
> fi ne. A StringBuilder object can clearly go in an Object[]. The problem is that we don’t
> actually have an Object[]. We have a String[] referred to from an Object[] variable. At
> runtime, the code throws an ArrayStoreException. You don’t need to memorize the name
> of this exception, but you do need to know that the code will throw an exception.

I didn't understand why it throws arraystoreexception? It says in the explanation that we actually dont have an Object[], how come?

**Comment by lifeanddeath** [comment]
@FatihBozik

**Comment by FatihBozik** [comment]
Hi @lifeanddeath,

We should consider the object as the entity that exists in memory. Regardless of the type of the reference that we have for the object in memory, the object itself doesn’t change.

`The String[]` object is created in line 3 and stored in memory. The String array in memory is accessed with an object array type reference in line 4. We have String array in memory. We don’t actually have an `Object[]`. Lastly, JVM throws `java.lang.ArrayStoreException` in line 7, trying to store the StringBuilder data type in a String array.

**Comment by lifeanddeath** [comment]
Thank you very much, so can we say that **objects**, **againStrings**  instances from line 4-5, respectively, actually points at the object created at line 1?

**Comment by FatihBozik** [comment]
Yes, that's right.
