### ISSUE TITLE
== operator

### ISSUE THREAD

**Issue by lifeanddeath** [lifeanddeath/oracle-certification-javaSE8-programmer#3]
In the following class;
**oracle-certification-javaSE8-programmer/src/coreJavaAPIs/EqualsExample.java** 

Second if condition succesfully propagates, however, ''=='' operator is actually also checking the object reference, although they are different data types meaning they are held in different areas of the memory heap, how could they be the same?

Code snippet as follows:

```
public static void main(String[] args) {
		String number = "1";
		int value = 1;
		boolean result = true;
		
		if (number.equals(value)) System.out.println("They are equal -1-"); // it would compile but not work
		if (Integer.parseInt(number) == value) System.out.println("This also works -2-"); //works
		if (number.equals(String.valueOf(value))) System.out.println("This might not work -3-"); //works
		
		// if (number == value )  // wouldn't work because they are different types.
		if (number.equals(result)) System.out.println("dont expect that this works -4-");// equals doesn't care about type so it would compile but not work
	}
```

Although we cast it explicity to int, how come that they could be equal because they are stored in different memory addresses, as int and string is different types.

**Comment by lifeanddeath** [comment]
I simply update the following class and added new cases:

```
public static void main(String[] args) {
		String number = "1";
		int value = 1;
		boolean result = true;
		
		if (number.equals(value)) System.out.println("They are equal -1-"); // it would compile but not work
		if (Integer.parseInt(number) == value) System.out.println("This also works -2-"); //works
		if (number.equals(String.valueOf(value))) System.out.println("This might not work -3-"); //works
		
		// if (number == value )  // wouldn't work because they are different types.
	    if (number.equals(result)) System.out.println("dont expect that this works -4-");// equals doesn't care about type so it would compile but not work
	    
	    String a = "";
	    a += "2";
	    a += "c";
	    a += "false";
	    
	    System.out.println(a); 
	    
	    if ( a == "2cfalse") System.out.println("==");
	    if (a.equals("2cfalse")) System.out.println("equals");
	    
	    String b  = "example";
	    if (b == "example")  System.out.println("this works"); // it does work
	}
```

In this case, the string a is initially set to ""; then it results in being "2cfalse" then why it doesn't work with the first if condition where the result would be printing "==" ?  If it doesn't work the last if condition with string B should also not work.

My impression is that, when we propagate or alter the strings content, it is referring to a new object for every new manipulation is it  correct dear Fatih or? If this is the case, I still don't undertand the logic behind:

`if (Integer.parseInt(number) == value) System.out.println("This also works -2-"); //works`

this if condition in the beginning and how it works.

**Comment by FatihBozik** [comment]
> when we propagate or alter the strings content, it is referring to a new object for every new manipulation

Yes @lifeanddeath, that's true. Remember that a String class is immutable which means once created cannot be changed. Therefore, when you call `+` operator on a String, a new String object is created. 
The old String remains as it is.

Also, if you don't use new keyword like below. New object goes to String pool.
```java
String b  = "example";
```
Then, if you use "example" literal String another place, new object is not created, the object in the string pool is returned.

**Comment by lifeanddeath** [comment]
Thanks, what about the first part with first if condition?

**Comment by FatihBozik** [comment]
`Integer.parseInt(String)` method returns a primitive integer and not an `Integer` object.
The second condition checks the equation 1 == 1 and the answer is clearly correct.

**Comment by lifeanddeath** [comment]
Thanks a lot Fatih!

**Comment by FatihBozik** [comment]
Be careful, Java convert wrapper type to primitive int when you compare primitive int and wrapper Integer object.

```java
int primitiveInt = 5;
String numberAsString = "5";

if(new Integer(numberAsString) == primitiveInt) {
    // This works because of Java convert wrapper types 
    // to primitive int before comparison when you compare 
    // primitive and wrapper object
    System.out.println("Works");
}
```

See: https://stackoverflow.com/a/34554444/2763057
